### PR TITLE
[WIP] Changes for Samsung Galaxy S7 (herolte) port

### PR DESCRIPTION
**Pull request by ZeroPointEnergy**
This are some required changes for the herolte (Samsung Galaxy S7) port in order for it to build.

I'm not really familiar with Android and Halium, so I don't know if everything is in the right place or even implemented correctly. Please advice if I need to change something.

### CODE REVIEW

**Comment by lnjX** [comment]
Why are the changes to the init script and makefile necessary? You can just edit your kernel config and the fstab.

**Comment by ZeroPointEnergy** [comment]
I excluded the additional fstab because this may very well cause problems for other ports in the future and this way it's solved for all of them. But I can remove that code again and just fork and remove that file from the device tree.

Is the check for CONFIG_ANDROID_LOW_MEMORY_KILLER really needed? mer-kernel-check sais it is not.

**Comment by lnjX** [comment]
Please resolve the merge conflicts and may have a look at halium-boot, it will replace hybris-boot soon.

**Comment by ZeroPointEnergy** [comment]
Yes, I'm already in the progress of switching to halium-boot. Will do

**Pull request merged**
